In [ ]:
# Task: Create a 1D array of even numbers and reshape it into a 5*2 matrix
import numpy as np
arr = np.arange(0, 19, 2)  
arr_2d = arr.reshape(5, 2) 
print(arr_2d)


[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]


In [ ]:
# Task: Generate a random 3*4 array and replace all negative values with 0 using boolean masking
import numpy as np
arr = np.random.randint(-6, 7, size=(3, 4))
print("Original array:") 
print(arr)
arr[arr < 0] = 0
print("Array after replacing negatives with 0:")
print(arr)

Original array:
[[-3 -6  3  6]
 [ 5 -5 -4  5]
 [-2 -1 -6  2]]
Array after replacing negatives with 0:
[[0 0 3 6]
 [5 0 0 5]
 [0 0 0 2]]


In [ ]:
# Task: perform vectorized arithmetic operations on two random 3*3 matrices
import numpy as np
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
result = (A + B) * (-A / 2)
print(result)

[[-0.23485099 -0.10565201 -0.54441832]
 [-0.67710241 -0.52418479 -0.30070232]
 [-0.98427625 -0.08983072 -0.64813715]]


In [ ]:
# Task: Combine two arrays horizontally (axis = 1) to merge datasets
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.concatenate((arr1, arr2),axis=1)
print("Horizontal concatenation:")
print(result)

Horizontal concatenation:
[[1 2 5 6]
 [3 4 7 8]]
